Provider: Yaml
MySql:
  Host: "127.0.0.1"
  Port: "3306"
  Database: "friendsystem"
  User: "root"
  Password: "cheesecake"
MongoDB:
  Uri: ""
  Database: "friendsystem"

Messages:
  Prefix: "&8» &eFriendSystem &8| &7"
  NoPermission: "&cYou have insufficient permissions to execute this command."
  FriendYourself: "&cYou can't be friends with yourself."
  SendRequest: "&aA friend request was sent to &7[0]&a."
  FriendAccepted: "&aYou accepted &7[0]'s &afriend request."
  FriendDenied: "&aYou denied &7[0]'s &afriend request."
  FriendRemoved: "&7[0] &ais no longer on your friends list."
  AlreadySendRequest: "&cA friend request has already been sent to &7[0]&c."
  RequestDenied: "&7[0] &cdid not accept your request."
  RequestAccepted: "&7[0] &ahas accepted your request."
  RequestReceived: "&7[0] &asent you a friend request. You can accept it with &e/friend accept [0]&a."
  AlreadyFriends: "&cYou're already friends with &7[0]&c."
  UserDoesNotExist: "&cThis user does not exist."
  NotOnFriendList: "&7[0] &cis not your friend."
  NoFriends: "&cYou do not have any friends."
  NoRequests: "&cYou do not have any requests."
  RequestNotExists: "&cThis player has not sent you a friend request."
  CannotRequest: "&cYou cannot send a friend request to this player."
  FriendslistInfo: "&aHere's a list of your friends:"
  RequestlistInfo: "&aHere's a list of your friend requests:"
  FriendlistFormat: "&7-> &e[0]"
  RequestlistFormat: "&7-> &e[0]"
  JoinNotification: "&7There are currently &e[0] &7friends online."
  FriendJoined: "&7[0] &ais now online."
  FriendLeft: "&7[0] &cis now offline."
  RequestTrue: "&aYou are now receiving requests."
  RequestFalse: "&cYou will now receive no more requests."
  NotificationTrue: "&aYou will now receive notifications."
  NotificationFalse: "&cYou will no longer receive any notifications."

HelpFormat:
  Header: "&8-=-=-=- &eHelp &8-=-=-=-"
  Help: "&e/friend help &8- &7Show this messages."
  Add: "&e/friend add <Player> &8- &7Add a friend."
  Remove: "&e/friend remove <Player> &8- &7Remove a friend."
  Accept: "&e/friend accept <Player> &8- &7Accept a friend request."
  Deny: "&e/friend deny <Player> &8- &7Deny a friend request."
  List: "&e/friend list &8- &7Show a list of all your friends."
  Requests: "&e/friend requests &8- &7Show a list of friend requests."
  Togglenotify: "&e/friend togglenotify &8- &7Toggle receiving of online-/offline messages."
  Togglerequests: "&e/friend togglerequests &8- &7Toggle getting requests."
  Footer: "&8-=-=-=- &eHelp &8-=-=-=-"

Commands:
  Friend: "friend"